"""initial migration

Revision ID: b4fb83e5146f
Revises: 
Create Date: 2025-11-06 15:55:19.481607

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b4fb83e5146f'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Accounts',
    sa.Column('id', sa.BigInteger(), autoincrement=False, nullable=False),
    sa.Column('phone_number', sa.String(length=20), nullable=False),
    sa.Column('session_string', sa.String(length=512), nullable=False),
    sa.Column('api_id', sa.BigInteger(), nullable=False),
    sa.Column('api_hash', sa.String(length=100), nullable=False),
    sa.Column('username', sa.String(length=255), nullable=True),
    sa.Column('messages_rest', sa.BigInteger(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('api_hash'),
    sa.UniqueConstraint('api_id'),
    sa.UniqueConstraint('id'),
    sa.UniqueConstraint('phone_number'),
    sa.UniqueConstraint('session_string'),
    sa.UniqueConstraint('username')
    )
    op.create_table('Campaigns',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('promt', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('InviteCodes',
    sa.Column('value', sa.String(length=32), nullable=False),
    sa.Column('used', sa.Boolean(), nullable=False),
    sa.Column('notation', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('value')
    )
    op.create_table('Dialogs',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('username', sa.String(length=100), nullable=False),
    sa.Column('account_id', sa.BigInteger(), nullable=True),
    sa.Column('campaign_id', sa.BigInteger(), nullable=False),
    sa.Column('status', sa.String(length=10), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['Accounts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['campaign_id'], ['Campaigns.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Users',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('username', sa.String(length=32), nullable=False),
    sa.Column('password_hash', sa.String(length=100), nullable=False),
    sa.Column('invite_code', sa.String(length=32), nullable=False),
    sa.ForeignKeyConstraint(['invite_code'], ['InviteCodes.value'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Messages',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('dialog_id', sa.BigInteger(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('from_user', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['dialog_id'], ['Dialogs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Messages')
    op.drop_table('Users')
    op.drop_table('Dialogs')
    op.drop_table('InviteCodes')
    op.drop_table('Campaigns')
    op.drop_table('Accounts')
    # ### end Alembic commands ###
