"""unique dialogs by username

Revision ID: fae2b2a9903c
Revises: b4fb83e5146f
Create Date: 2025-11-06 15:57:19.952838

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fae2b2a9903c'
down_revision: Union[str, Sequence[str], None] = 'b4fb83e5146f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'Dialogs', ['username'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'Dialogs', type_='unique')
    # ### end Alembic commands ###
